name: Update ASX franking cache

on:
  schedule:
    - cron:  '0 2 * * *'      # 02:00 UTC daily
  workflow_dispatch:         # allows manual runs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install playwright pandas beautifulsoup4 yfinance
          python -m playwright install chromium

      - name: Run scraper
        run: python scrape_fran_cache.py

      - name: Commit updated cache
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add franking_cache.json
          git diff --quiet --exit-code || git commit -m "📈 Update franking cache"

      - uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
